version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  # MongoDB service
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./ufc_database.ufc_fighters.json:/data/ufc_database.ufc_fighters.json:ro
      - ./ufc_database.ufc_fight_1.json:/data/ufc_database.ufc_fight_1.json:ro
    environment:
      - MONGO_INITDB_DATABASE=ufc_database

  dash_app:
    build: .
    environment:
      - MONGODB_HOST=mongodb
      - ELASTICSEARCH_HOST=elasticsearch
    ports:
      - "8050:8050"
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - .:/app

  es_initializer:
    image: appropriate/curl:latest
    depends_on:
      - elasticsearch
    command: >
      /bin/sh -c "
        until curl --output /dev/null --silent --head --fail http://elasticsearch:9200; do
          echo 'Waiting for Elasticsearch...'
          sleep 5
        done;
        echo 'Elasticsearch is up!';
        curl -X PUT http://elasticsearch:9200/ufc-index;
      "

volumes:
  mongodb_data_container:
  elasticsearch_data:



